# Generated by Django 4.1.5 on 2023-01-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_original', models.URLField()),
                ('url_curta', models.CharField(max_length=30)),
                ('data_hora_de_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
