# Generated by Django 4.1.5 on 2023-01-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='url_curta',
            field=models.CharField(max_length=10),
        ),
    ]
