# Generated by Django 4.1.5 on 2023-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_alter_links_url_curta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='url_curta',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
